### ISSUE TITLE
sidebar and footer modules look wonky

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#151] opened 2017-08-06 12:16 UTC
I don't know if it's a bad ad messing up the code, but the the titles that usually center nicely over sidebar images are underneath and the footer module has weirdly sized images. It looked fine 2 days ago. Thank you.

**Comment by debperelman** [comment] 2017-08-22 18:56
I'd like to bump this. It's been over 2 weeks. Thanks.

**Comment by michiecat** [comment] 2017-08-22 20:42
I see what you mean! I'm looking into this and will comment here when I have some more information.

**Comment by michiecat** [comment] 2017-08-24 17:50
@debperelman I've just pushed a fix for this. The problem was that the image widget was recently updated in the latest version of WordPress. As a result of that update, the CSS class names associated with the widget also changed. This caused the associated styling to break. I've just updated your theme to use the latest class names.  Let us know if you see any other issues with this.

**Comment by debperelman** [comment] 2017-09-04 13:23
@michiecat Thank you for addressing this. They mostly look good now but the one at the bottom is still odd and I can't find in the new image widget how to correct the caption so it doesn't overlay. 
![screen shot 2017-09-04 at 9 21 06 am](https://user-images.githubusercontent.com/16911319/30028340-a834c5e0-9152-11e7-93bb-4c7f4ad8b3f5.png)

**Comment by michiecat** [comment] 2017-09-07 17:51
@debperelman the caption in footer image widget overlays by design (e.g. this is controlled in the theme's CSS, and not the image widget). Did you want this caption to appear below the image instead? Let me know, and I'll get it fixed for you!

**Comment by debperelman** [comment] 2017-09-07 20:45
It was previously the caption if you hovered on the image. If that's not possible, I'd rather just remove it.

**Comment by michiecat** [comment] 2017-09-08 03:49
@debperelman OK, I'm working on a fix for this!

**Comment by debperelman** [comment] 2017-09-27 01:02
I'd like to bump this as it still has the caption spread over the image. Further, the decorative borders aren't showing up on all the widgets anymore in the sidebar. I swapped a "fall" image (the apples) for the "summer" one that had been here and the caption no longer works. Thanks.
![screen shot 2017-09-26 at 9 01 23 pm](https://user-images.githubusercontent.com/16911319/30890928-e66fab1a-a2fd-11e7-94b2-910ca95fa4bb.png)

**Comment by michiecat** [comment] 2017-09-27 07:31
@debperelman my apologies, I'll push the fix tomorrow.

**Closed** 2017-09-29 07:39 UTC
Labels: high-priority

**Comment by michiecat** [comment] 2017-09-29 08:20
@debperelman I've pushed a fix for this. The caption now only appears on hover.
