### ISSUE TITLE
non-https sources?

### ISSUE THREAD

**Issue by debperelman** [a8cteam51/smittenkitchen#128] opened 2016-07-27 00:29 UTC
Just a quick question about an email I got from a reader whose wife is now having trouble reaching the site. My understanding of http vs. https is very limited (I mean, aside from what I can Google) and I also don't know if there is any veracity to this concern. He says: 

> ...aspects of the page, and content, come from non-https sources, which confuses her Blackberry and any browser with HTTPs-everywhere installed. 

Does this complaint make sense and is it something others might be concerned about if so?

**Comment by michiecat** [comment] 2016-07-31 06:16
According to https://vip.wordpress.com/documentation/ssl-for-vip-sites/#important-notes, the SSL implementation that WordPress.com VIP uses is SNI based, which is not supported by older versions of some browsers. I'm not sure which version of Blackberry your reader was using, but according to this table (https://en.wikipedia.org/wiki/Server_Name_Indication#Support), Blackberry 7.1 or earlier is not supported. If they're using Blackberry 10 or newer, HTTPS should be fully supported. If you're able to find out which version of Blackberry your reader was using, we can confirm if this is indeed the issue. 

Unfortunately I doubt there will be much we can do on our end, but I can check with the VIP team this week.

**Comment by michiecat** [comment] 2016-08-01 22:38
I checked with the VIP team and my haunches in the above comment could be the cause of your reader's issues with Blackberry. If you're able to get the version of Blackberry she's using, we can double-check that this is the case.

**Comment by sarahmonster** [comment] 2016-08-03 09:58
It sounds like this might be related to the mixed-content issue mentioned in #13. The site still shows a mixed-content warning, I think due to these ad-related files:

http://tags.crwdcntrl.net/c/8753/cc_af.js
http://smittenkitchen.com/prebid-js/

For a bit of background on why mixed-content warnings are problematic, you can read this article: http://www.howtogeek.com/181911/htg-explains-what-exactly-is-a-mixed-content-warning/

Basically it boils down to "https is good because it's secured" and "anything that's sent via an insecure connection could potentially collect information entered by your users." As a result, browsers try to protect users by blocking the insecure bits.

It'd be great to see these mixed-content warnings ironed out but I think you'd need to talk to your ad people about that. I've managed to fix the problem with the tags JS, but I can't fix the prebid URL—the URL that's being loaded is different from the one I've specified in the code here https://github.com/a8cteam51/smittenkitchen/blob/25c6bcfd8a10e21c6ee6a8726302ac92d3bd2b80/inc/ads.php#L78.

@debperelman, if you can ask your ad people to ensure that the prebid file is loaded via https, rather than http, this may resolve the issue.

**Comment by sarahmonster** [comment] 2016-12-15 11:18
It looks as though the mixed-content warnings are gone from the site now—perhaps fixed by #143?

**Closed by sarahmonster** 2016-12-15 11:18 UTC
Labels: conversation, help wanted
